version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t email-validator-app -f Build/Dockerfile .

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Pull Docker image
          command: docker pull email-validator-app || docker build -t email-validator-app -f Build/Dockerfile .
      - run:
          name: Run the Docker container
          command: docker run -d -p 3000:3000 --name email-validator-app-container email-validator-app
      - run:
          name: Wait for server to start
          command: |
            # Wait for up to 20 seconds for the server to start
            for i in `seq 1 20`; do
              nc -z localhost 3000 && echo "Server is up!" && exit 0
              echo "Waiting for server..."
              sleep 1
            done
            echo "Server failed to start in time" && exit 1
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Cleanup Docker container
          command: docker stop email-validator-app-container && docker rm email-validator-app-container

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
