version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t email-validator-app  .

  test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Dependencies
          command: npm install
          
      - run:
          name: Pull Docker image
          command: docker pull email-validator-app || docker build -t email-validator-app .
          
      - run:
          name: Run the Docker container
          command: docker run -d -p 3000:3000 --name email-validator-app-container email-validator-app
          
      - run:
          name: Run tests
          command: docker exec email-validator-app-container npm test > test-results.txt

      - run:
          name: Save Test Results as Artifacts
          command: mv test-results.txt /tmp/test-results.txt

      - store_artifacts:
          path: /tmp/test-results.txt
          destination: test-results

          
      - run:
          name: Cleanup Docker container
          command: docker stop email-validator-app-container && docker rm email-validator-app-container




workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
